services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_digital_prescriptions
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    container_name: redis_bull
    ports:
      - "6379:6379"

volumes:
  mongodb_data: